-- Bronze: Raw Account Balances (F0902_WH) from JDE
-- Source workflow: wf_T_BL_ACCTBAL_ZJ
SELECT
    CAST(GLCO   AS VARCHAR(5))   AS GLCO,
    CAST(GLAID  AS VARCHAR(8))   AS GLAID,
    CAST(GLMCU  AS VARCHAR(12))  AS GLMCU,
    CAST(GLOBJ  AS VARCHAR(6))   AS GLOBJ,
    CAST(GLSUB  AS VARCHAR(8))   AS GLSUB,
    CAST(GLLDA  AS VARCHAR(1))   AS GLLDA,
    CAST(GLLT   AS VARCHAR(2))   AS GLLT,
    CAST(GLCRCD AS VARCHAR(3))   AS GLCRCD,
    GLFY,
    GLPN,
    GLAN01, GLAN02, GLAN03, GLAN04, GLAN05, GLAN06,
    GLAN07, GLAN08, GLAN09, GLAN10, GLAN11, GLAN12, GLAN13, GLAN14,
    GLODOC,
    CAST(GLODCT AS VARCHAR(2))   AS GLODCT,
    CAST(GLSFX  AS VARCHAR(3))   AS GLSFX,
    CAST(GLR1   AS VARCHAR(8))   AS GLR1,
    CAST(GLR2   AS VARCHAR(8))   AS GLR2,
    CAST(GLR3   AS VARCHAR(8))   AS GLR3,
    CURRENT_TIMESTAMP()          AS ETL_LOAD_DTE,
    'JDE'                        AS RECORD_SOURCE
FROM {{ this.database }}.BRONZE.BRZ_F0902_WH_RAW
