-- Bronze: Raw Work Order Master (F4801_WH) from JDE
-- Source workflow: wf_S_ZJ_WO_ROBAR_BATCHES
SELECT
    CAST(WADCTO AS VARCHAR(2))   AS WADCTO,
    WADOCO,
    CAST(WASFXO AS VARCHAR(3))   AS WASFXO,
    CAST(WATYPS AS VARCHAR(1))   AS WATYPS,
    CAST(WASTCM AS VARCHAR(30))  AS WASTCM,
    CAST(WAMMCU AS VARCHAR(12))  AS WAMMCU,
    CAST(WALITM AS VARCHAR(25))  AS WALITM,
    CAST(WAVR01 AS VARCHAR(25))  AS WAVR01,
    CAST(WAMCU  AS VARCHAR(12))  AS WAMCU,
    WAMOH,
    WAURAT,
    CAST(WAAITM AS VARCHAR(25))  AS WAAITM,
    CURRENT_TIMESTAMP()          AS ETL_LOAD_DTE,
    'JDE'                        AS RECORD_SOURCE
FROM {{ this.database }}.BRONZE.BRZ_F4801_WH_RAW
