-- Bronze: Raw Business Unit Master (F0006_WH) from JDE
-- Source workflow: wf_T_BL_ACCTBAL_ZJ
SELECT
    CAST(MCMCU  AS VARCHAR(12))  AS MCMCU,
    CAST(MCSTYL AS VARCHAR(2))   AS MCSTYL,
    CAST(MCDC   AS VARCHAR(40))  AS MCDC,
    CAST(MCLDM  AS VARCHAR(1))   AS MCLDM,
    CAST(MCCO   AS VARCHAR(5))   AS MCCO,
    MCAN8,
    MCAN8O,
    CAST(MCCNTY AS VARCHAR(3))   AS MCCNTY,
    CAST(MCADDS AS VARCHAR(3))   AS MCADDS,
    CAST(MCFMOD AS VARCHAR(1))   AS MCFMOD,
    CAST(MCDL01 AS VARCHAR(30))  AS MCDL01,
    CAST(MCDL02 AS VARCHAR(30))  AS MCDL02,
    CAST(MCDL03 AS VARCHAR(30))  AS MCDL03,
    CAST(MCDL04 AS VARCHAR(30))  AS MCDL04,
    CAST(MCPECC AS VARCHAR(1))   AS MCPECC,
    CAST(MCCRCD AS VARCHAR(3))   AS MCCRCD,
    CURRENT_TIMESTAMP()          AS ETL_LOAD_DTE,
    'JDE'                        AS RECORD_SOURCE
FROM {{ this.database }}.BRONZE.BRZ_F0006_WH_RAW
